const DEFAULT_INTERVAL_MS = 1000;
const DEFAULT_AUTO_START = true;
const DEFAULT_SHOW_DAYS = false;
const DEFAULT_SHOW_HOURS = false;
const DEFAULT_SHOW_MINUTES = true;
const DEFAULT_SHOW_SECONDS = true;
const DEFAULT_SHOW_MILLISECONDS = false;
const DEFAULT_SEPARATOR = ':';
const DEFAULT_SKIP_EXITING = false;
const DEFAULT_SKIP_ENTERING = true;

export {
  DEFAULT_INTERVAL_MS,
  DEFAULT_AUTO_START,
  DEFAULT_SHOW_DAYS,
  DEFAULT_SHOW_HOURS,
  DEFAULT_SHOW_MINUTES,
  DEFAULT_SHOW_SECONDS,
  DEFAULT_SHOW_MILLISECONDS,
  DEFAULT_SEPARATOR,
  DEFAULT_SKIP_EXITING,
  DEFAULT_SKIP_ENTERING,
};
