const DEFAULT_INTERVAL_MS = 1000;
const DEFAULT_AUTO_START = true;
const DEFAULT_SKIP_EXITING = false;
const DEFAULT_SKIP_ENTERING = true;

export {
  DEFAULT_AUTO_START,
  DEFAULT_INTERVAL_MS,
  DEFAULT_SKIP_ENTERING,
  DEFAULT_SKIP_EXITING,
};
