const DEFAULT_INTERVAL_MS = 16;
const DEFAULT_AUTO_START = false;
const DEFAULT_SKIP_EXITING = false;
const DEFAULT_SKIP_ENTERING = true;

export {
  DEFAULT_INTERVAL_MS,
  DEFAULT_AUTO_START,
  DEFAULT_SKIP_EXITING,
  DEFAULT_SKIP_ENTERING,
};
