const DEFAULT_ANIMATION_DELAY = 0;
const DEFAULT_ANIMATION_DISTANCE = 80;
const DEFAULT_ANIMATION_DURATION = 1200;

export {
  DEFAULT_ANIMATION_DELAY,
  DEFAULT_ANIMATION_DISTANCE,
  DEFAULT_ANIMATION_DURATION,
};
